#!/usr/bin/env ruby

require 'prime_multiplication_table'

if ARGV.empty?
  puts "Usage: pmt <number> [ATKINS | ERASTOTHENES | TRIAL]"
else
  cli = PrimeMultiplicationTable::CLI.new
  command = cli.load_command(ARGV.join(" "))
  cli.run(command)
end
